// Generated by stitch2 tokens from DESIGN.md (Material roles: seed #E8662C, fidelity). Do not edit.
// Load after the Tailwind CDN script: bg-floor, text-chalk, bg-ember, rounded-card, p-lg, font-mono, bg-md-primary-container. Text styles: the .type-<level> classes in tokens.css.
tailwind.config = {
  "darkMode": [
    "selector",
    "[data-theme='dark']"
  ],
  "theme": {
    "extend": {
      "colors": {
        "floor": "var(--gg-floor)",
        "iron": "var(--gg-iron)",
        "raised": "var(--gg-raised)",
        "hairline": "var(--gg-hairline)",
        "chalk": "var(--gg-chalk)",
        "steel": "var(--gg-steel)",
        "faint": "var(--gg-faint)",
        "ember": "var(--gg-ember)",
        "ember-pressed": "var(--gg-ember-pressed)",
        "ember-wash": "var(--gg-ember-wash)",
        "success": "var(--gg-success)",
        "warning": "var(--gg-warning)",
        "danger": "var(--gg-danger)",
        "paper": "var(--gg-paper)",
        "md": {
          "background": "var(--md-background)",
          "on-background": "var(--md-on-background)",
          "surface": "var(--md-surface)",
          "surface-dim": "var(--md-surface-dim)",
          "surface-bright": "var(--md-surface-bright)",
          "surface-container-lowest": "var(--md-surface-container-lowest)",
          "surface-container-low": "var(--md-surface-container-low)",
          "surface-container": "var(--md-surface-container)",
          "surface-container-high": "var(--md-surface-container-high)",
          "surface-container-highest": "var(--md-surface-container-highest)",
          "on-surface": "var(--md-on-surface)",
          "surface-variant": "var(--md-surface-variant)",
          "on-surface-variant": "var(--md-on-surface-variant)",
          "inverse-surface": "var(--md-inverse-surface)",
          "inverse-on-surface": "var(--md-inverse-on-surface)",
          "outline": "var(--md-outline)",
          "outline-variant": "var(--md-outline-variant)",
          "shadow": "var(--md-shadow)",
          "scrim": "var(--md-scrim)",
          "surface-tint": "var(--md-surface-tint)",
          "primary": "var(--md-primary)",
          "on-primary": "var(--md-on-primary)",
          "primary-container": "var(--md-primary-container)",
          "on-primary-container": "var(--md-on-primary-container)",
          "inverse-primary": "var(--md-inverse-primary)",
          "secondary": "var(--md-secondary)",
          "on-secondary": "var(--md-on-secondary)",
          "secondary-container": "var(--md-secondary-container)",
          "on-secondary-container": "var(--md-on-secondary-container)",
          "tertiary": "var(--md-tertiary)",
          "on-tertiary": "var(--md-on-tertiary)",
          "tertiary-container": "var(--md-tertiary-container)",
          "on-tertiary-container": "var(--md-on-tertiary-container)",
          "error": "var(--md-error)",
          "on-error": "var(--md-on-error)",
          "error-container": "var(--md-error-container)",
          "on-error-container": "var(--md-on-error-container)",
          "primary-fixed": "var(--md-primary-fixed)",
          "primary-fixed-dim": "var(--md-primary-fixed-dim)",
          "on-primary-fixed": "var(--md-on-primary-fixed)",
          "on-primary-fixed-variant": "var(--md-on-primary-fixed-variant)",
          "secondary-fixed": "var(--md-secondary-fixed)",
          "secondary-fixed-dim": "var(--md-secondary-fixed-dim)",
          "on-secondary-fixed": "var(--md-on-secondary-fixed)",
          "on-secondary-fixed-variant": "var(--md-on-secondary-fixed-variant)",
          "tertiary-fixed": "var(--md-tertiary-fixed)",
          "tertiary-fixed-dim": "var(--md-tertiary-fixed-dim)",
          "on-tertiary-fixed": "var(--md-on-tertiary-fixed)",
          "on-tertiary-fixed-variant": "var(--md-on-tertiary-fixed-variant)"
        }
      },
      "borderRadius": {
        "sm": "8px",
        "input": "12px",
        "btn": "14px",
        "row": "16px",
        "card": "20px",
        "sheet": "24px",
        "full": "9999px"
      },
      "spacing": {
        "xs": "4px",
        "sm": "8px",
        "md": "12px",
        "lg": "16px",
        "xl": "24px",
        "2xl": "32px",
        "3xl": "48px",
        "page": "16px"
      },
      "fontFamily": {
        "sans": [
          "Geist",
          "system-ui",
          "sans-serif"
        ],
        "mono": [
          "Geist Mono",
          "ui-monospace",
          "monospace"
        ]
      }
    }
  }
}
