/**
 * Bundles a project's elements entry (the file that calls defineElements from stitch2/elements) into one
 * script for the screens, with esbuild: JSX, TypeScript and the project's own dependencies (React and its
 * components) resolved from the entry's folder.
 * Usage: stitch2 elements <entry> [--out <file>]   (default <design>/components/<prefix>.elements.js)
 */
import { resolve } from 'node:path'
import { build } from 'esbuild'
import { BASE, config } from './config.ts'
import { ROOT } from './screens.ts'

const args = process.argv.slice(2)
const entry = args.find((a) => !a.startsWith('--'))
if (!entry) {
  console.error('usage: stitch2 elements <entry> [--out <file>]')
  process.exit(1)
}
const outIndex = args.indexOf('--out')
const out = outIndex >= 0 ? resolve(BASE, args[outIndex + 1]!) : resolve(ROOT, `components/${config.prefix}.elements.js`)
await build({
  entryPoints: [resolve(BASE, entry)],
  outfile: out,
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2022',
  jsx: 'automatic',
  define: { 'process.env.NODE_ENV': '"production"' },
  minify: true,
  legalComments: 'none',
  banner: { js: `/* Generated by stitch2 elements from ${entry}. Do not edit. */` },
  logLevel: 'warning',
})
console.log(`elements: ${entry} → ${out.replace(`${BASE}/`, '')}`)

