/**
 * Design tokens for lab screens, generated from design/DESIGN.md's front matter (the DESIGN.md format Stitch
 * and Google's design.md linter use), plus Material 3 colour roles from one seed with Google's
 * material-color-utilities (settings in tokens.config.json next to DESIGN.md).
 * Writes tokens.css (colour variables, dark by default and [data-theme=light], and one .type-<level>
 * class per typography level) and tailwind.tokens.js (a Tailwind CDN config using the variables).
 * Usage: stitch2 tokens
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  argbFromHex,
  type DynamicScheme,
  Hct,
  hexFromArgb,
  MaterialDynamicColors,
  SchemeContent,
  SchemeExpressive,
  SchemeFidelity,
  SchemeFruitSalad,
  SchemeMonochrome,
  SchemeNeutral,
  SchemeRainbow,
  SchemeTonalSpot,
  SchemeVibrant,
} from '@material/material-color-utilities'
import { config as lab } from './config.ts'
import { readDesign } from './design-md.ts'
import { ROOT } from './screens.ts'

type SchemeClass = new (source: Hct, isDark: boolean, contrast: number) => DynamicScheme
const SCHEMES: Record<string, SchemeClass> = {
  fidelity: SchemeFidelity,
  tonal_spot: SchemeTonalSpot,
  vibrant: SchemeVibrant,
  expressive: SchemeExpressive,
  content: SchemeContent,
  neutral: SchemeNeutral,
  monochrome: SchemeMonochrome,
  rainbow: SchemeRainbow,
  fruit_salad: SchemeFruitSalad,
}

const config = JSON.parse(readFileSync(join(ROOT, 'tokens.config.json'), 'utf8')) as {
  seed: string
  scheme: string
  contrast?: number
}
const Scheme = SCHEMES[config.scheme]
if (!Scheme)
  throw new Error(`unknown scheme "${config.scheme}"; use one of ${Object.keys(SCHEMES).join(', ')}`)
const design = readDesign()
const seed = design.colors[config.seed] ?? config.seed
const source = Hct.fromInt(argbFromHex(seed))

/** Every Material role for one mode, keyed like "primary-container". */
function roles(dark: boolean): Record<string, string> {
  const scheme = new Scheme(source, dark, config.contrast ?? 0)
  const out: Record<string, string> = {}
  // The roles are static DynamicColor properties of MaterialDynamicColors (0.3.x).
  const all = Object.values(MaterialDynamicColors).filter(
    (c): c is { name: string; getArgb: (s: DynamicScheme) => number } =>
      typeof c === 'object' && c !== null && 'getArgb' in c && 'name' in c,
  )
  for (const color of all) {
    if (color.name.endsWith('_palette_key_color')) continue
    out[color.name.replaceAll('_', '-')] = hexFromArgb(color.getArgb(scheme))
  }
  return out
}

// DESIGN.md colours: plain names are the dark theme, light-<name> overrides them in the light theme.
const dark: Record<string, string> = {}
const light: Record<string, string> = {}
for (const [name, value] of Object.entries(design.colors)) {
  if (name === 'primary') continue
  if (name.startsWith('light-')) light[name.slice(6)] = value
  else dark[name] = value
}
for (const name of Object.keys(dark)) light[name] ??= dark[name]!

const vars = (selector: string, palette: Record<string, string>, md: Record<string, string>) =>
  [
    `${selector} {`,
    ...Object.entries(palette).map(([k, v]) => `  --${lab.prefix}-${k}: ${v};`),
    ...Object.entries(md).map(([k, v]) => `  --md-${k}: ${v};`),
    '}',
  ].join('\n')

// Scripts without case or with joined letters: no tracking, no caps, and room for tall marks.
const UNCASED = ['ar', 'zh', 'ko', 'th', 'hi'].map((l) => `:lang(${l})`)
const FALLBACK =
  '"Noto Sans Arabic", "Noto Sans Thai", "Noto Sans Devanagari", "PingFang SC", "Noto Sans SC", "Apple SD Gothic Neo", "Noto Sans KR", system-ui, sans-serif'
const typeRules = Object.entries(design.typography).map(([name, t]) => {
  const fallback = `var(--${lab.prefix}-font-${/mono/i.test(t.fontFamily ?? '') ? 'mono' : 'sans'}-fallback)`
  const decl = [
    `font: ${t.fontWeight} ${t.fontSize}/${t.lineHeight} "${t.fontFamily}", ${fallback}`,
    `letter-spacing: ${t.letterSpacing ?? '0em'}`,
    t.fontFeature ? `font-feature-settings: ${t.fontFeature}` : '',
    name.endsWith('-caps') ? 'text-transform: uppercase' : '',
  ].filter(Boolean)
  return `.type-${name} { ${decl.join('; ')}; }`
})
const typeCss = [
  ...typeRules,
  `${UNCASED.map((l) => `${l} [class*="type-"], [class*="type-"]${l}`).join(', ')} { letter-spacing: 0; text-transform: none; }`,
  `${['th', 'hi'].map((l) => `:lang(${l}) [class*="type-"]`).join(', ')} { line-height: 1.5; }`,
]

const md = { dark: roles(true), light: roles(false) }
const header = `/* Generated by stitch2 tokens from DESIGN.md (Material roles: seed ${seed}, ${config.scheme}). Do not edit. */`
writeFileSync(
  join(ROOT, 'tokens.css'),
  [
    header,
    vars(":root, [data-theme='dark']", dark, md.dark),
    vars("[data-theme='light']", light, md.light),
    ":root { color-scheme: dark; } [data-theme='light'] { color-scheme: light; }",
    `:root { --${lab.prefix}-font-sans-fallback: ${FALLBACK}; --${lab.prefix}-font-mono-fallback: ui-monospace, monospace; }`,
    '/* Typography levels: one class sets family, size, line height, weight, tracking and figures. */',
    typeCss.join('\n'),
    '',
  ].join('\n\n'),
)

const colors: Record<string, unknown> = Object.fromEntries(
  Object.keys(dark).map((k) => [k, `var(--${lab.prefix}-${k})`]),
)
colors.md = Object.fromEntries(Object.keys(md.dark).map((k) => [k, `var(--md-${k})`]))
const families = Object.values(design.typography).map((t) => t.fontFamily ?? '')
const tailwind = {
  darkMode: ['selector', "[data-theme='dark']"],
  theme: {
    extend: {
      colors,
      borderRadius: design.rounded,
      spacing: design.spacing,
      fontFamily: {
        sans: [families.find((f) => !/mono/i.test(f)) ?? 'Geist', 'system-ui', 'sans-serif'],
        mono: [families.find((f) => /mono/i.test(f)) ?? 'Geist Mono', 'ui-monospace', 'monospace'],
      },
    },
  },
}
writeFileSync(
  join(ROOT, 'tailwind.tokens.js'),
  `${header.replace('/*', '//').replace(' */', '')}\n// Load after the Tailwind CDN script: bg-floor, text-chalk, bg-ember, rounded-card, p-lg, font-mono, bg-md-primary-container. Text styles: the .type-<level> classes in tokens.css.\ntailwind.config = ${JSON.stringify(tailwind, null, 2)}\n`,
)
console.log(
  `tokens: ${Object.keys(dark).length} colours, ${typeRules.length} type levels, ${Object.keys(md.dark).length} Material roles (${config.scheme}, seed ${seed})`,
)
